#!/bin/sh
# bspwm config file

TERMINAL="alacritty"    # terminal emulator command
TERMINALC="Alacritty"   # terminal emulator class

# exec function: run only if not allready running
run() {
    if ! pgrep -f "$1"; then
        $1 &
    fi
}

### early start programs ###
run sxhkd                                               # keybindings
run "picom --daemon"                                    # compositor
run "dunst -config ~/.config/dunst/dunstrc"             # notification daemon
run nm-applet                                           # NetworkManager applet
run firewall-applet                                     # firewalld applet
numlockx on                                             # enable numlock
run ~/.script/wallpaper.sh                              # wallpaper script
run "aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log" # apparmor notification
run "polybar example"
run "xbanish"

# keyboard settings
setxkbmap it


ws1="I"
ws2="II"
ws3="III"
ws4="IV"
ws5="V"
ws6="VI"
ws7="VII"
ws8="VIII"
ws9="IX"
ws10="X"

### monitor settings ###
if xrandr -q | grep HDML1 | awk '{print $2}' | grep -q connected; then
    xrandr --output HDMI1 --above eDP1
    bspc monitor HDMI1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10
fi
xrandr --output eDP1 --primary
bspc monitor eDP1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10


## WM config ##
bspc config border_width                  2
bspc config window_gap                    0
bspc config top_padding                   24
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true


# default workspace # xprop -> WM_CLASS(string) -> second argument
bspc rule -a "firefox" desktop=$ws3
bspc rule -a "Tor Browser" desktop=$ws3
bspc rule -a "TelegramDesktop" desktop=$ws4
bspc rule -a "vlc" desktop=$ws5
bspc rule -a "qBittorrent" desktop=$ws5
bspc rule -a "Thunderbird" desktop=$ws7
bspc rule -a $TERMINALC:"alsamixer" desktop=$ws8
bspc rule -a $TERMINALC:"htop" desktop=$ws9
bspc rule -a $TERMINALC:"nmon" desktop=$ws9
bspc rule -a "Keybase" desktop=$ws10
bspc rule -a "Spotify" desktop=$ws6
#shellcheck disable=SC2035
bspc rule -a *:"spotify" desktop=$ws6
bspc rule -a "" desktop=$ws6    #spotify


# late start programs
run firefox
run telegram-desktop
run "$TERMINAL --class alsamixer -e alsamixer"
run "$TERMINAL --class htop -e htop"
run "$TERMINAL --class nmon -e nmon"
run spotify
run thunderbird
run "run_keybase -a"

# go to first workspace
sleep 5
bscp desktop -f focused:^1

