# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

auto_restart: false

matches:
    # Parenthesis
    - trigger: "("
      replace: "($|$)"

    - trigger: "["
      replace: "[$|$]"

    - trigger: "{"
      replace: "{$|$}"

    # Quotation marks
    - trigger: " \""
      replace: " \"$|$\""

    - trigger: " '"
      replace: " '$|$'"

    - trigger: " `"
      replace: " `$|$`"

    # Emoji
    - trigger: ":ok"
      replace: "👍"

    # Date
    - trigger: ":date"
      replace: "{{mydate}}"
      propagate_case: true  # side effect: trigger case independent
      vars:
        - name: mydate
          type: date
          params:
            format: "%d/%m/%Y"

    # # Shell commands
    # - trigger: ":shell"
    #   replace: "{{output}}"
    #   vars:
    #     - name: output
    #       type: shell
    #       params:
    #         cmd: "echo Hello from your shell"
